services:
  deploy:
    build: ./deploy/
    image: example_deploy:deploy
    volumes:
     - pkg:/scr/package

  test-3-6:
    build: ./test_3_6/
    image: example_test_3_6:test
    volumes:
     - pkg:/scr/package

volumes:
  pkg:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./package