services:
  deploy:
    build: ./deploy/
    image: pyorb_deploy:deploy
    volumes:
     - pkg:/scr/pyorb

volumes:
  pkg:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./pyorb